### ISSUE TITLE
Can't import AI file

### ISSUE THREAD

**Issue by geobrando** [maptime/maptime-logo#3]
Hey @almccon:

I know next to nothing about Adobe Ilustrator but was going to play around with the AI version of this that you committed.  I wasn't able to open it but ran into the problem noted [here](https://forums.creativecow.net/thread/245/863021).

I only get a "Text import" dialog box and the above post mentions:

> they saved, but didn't include the font files - have the client resave and send from illustrator with font files included OR convert to outlines and then resend.

Think this is the issue?

**Comment by geobrando** [comment]
Hi @almccon. Are you able to open the AI version ok?

**Comment by almccon** [comment]
Yeah, it works for me. Sorry I didn't spot this issue earlier.

Yeah, I assume it's a font thing. The font is Comfortaa, which is an open-licenced Google font. You can download it [here](http://www.dafont.com/comfortaa.font), among other places.

I'll create a README to explain that.

**Comment by almccon** [comment]
@geobrando if that solves your issue, feel free to close this.

**Comment by geobrando** [comment]
:+1:
